### PR TITLE
add PHP 8.0 version

### PR DESCRIPTION
**Pull request by mleutenegger**
As PHP8 is now officially released and Silverstripe supports it, there should also be a docker container sporting PHP8.

I have tried to add it by interpreting the structure of this repo, but if I have missunderstood, just point me towards the right solution and I will update the PR!

### CODE REVIEW

**Comment by brettt89** [comment]
Have pushed up a quick update now that the `master` branch has changed. Also repeated your string fix for the 8.0 float in Github tests for rest of the floats.

**Comment by brettt89** [comment]
Looks like `silverstripe/installer` is still broken for PHP 8 due to PHPUnit dependencies.

```
Problem 1
    - sminnee/phpunit[5.7.28, ..., 5.7.x-dev] require phpunit/php-code-coverage ^4.0.4 -> satisfiable by phpunit/php-code-coverage[4.0.4, ..., 4.0.8].
    - phpunit/php-code-coverage[4.0.4, ..., 4.0.8] require php ^5.6 || ^7.0 -> your php version (8.0; overridden via config.platform, actual: 7.4.13) does not satisfy that requirement.
    - Root composer.json requires sminnee/phpunit ^5.7 -> satisfiable by sminnee/phpunit[5.7.28, 5.7.29, 5.7.x-dev].
```

The docker builds appear to work, however the tests are failing due the composer issues with 'beta' support of PHP 8.0.

You could use the `Dockerfile`s to build locally, otherwise will have to wait until issues are fixed.

**Comment by mleutenegger** [comment]
Thanks for the input! I was trying to come back to this in the next few weeks, and I will have a look at the dependency-issues then.

**Comment by gligorkot** [comment]
@brettt89 any chance you could re-run those 8.0 Github actions to check if issues have been resolved now please?

**Comment by brettt89** [comment]
> @brettt89 any chance you could re-run those 8.0 Github actions to check if issues have been resolved now please?

Looks like still the same issues upstream. PHPUnit being used for Silverstripe 4 does not appear to support PHP 8 which is preventing Silverstripe Projects from being installed.

https://github.com/silverstripe/silverstripe-framework/issues/9832

**Pull request merged**
